name: Daily Reel Generator

on:
  schedule:
    - cron: "30 16 * * *"  # Runs at 10:00 PM IST (16:30 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip uninstall -y moviepy
          pip install -r requirements.txt
          pip show Pillow
          
          # Create necessary directories
          mkdir -p output
          mkdir -p fonts
          
          # Download Montserrat-Bold font if not exists
          if [ ! -f fonts/Montserrat-Bold.ttf ]; then
            wget -O fonts/Montserrat-Bold.ttf https://github.com/google/fonts/raw/main/ofl/montserrat/static/Montserrat-Bold.ttf
          fi
          
          # Initialize message_tracker.json if not exists
          if [ ! -f message_tracker.json ]; then
            echo '{"last_used_message": 0}' > message_tracker.json
          fi

      - name: Run Python script to generate reel
        run: |
          python generate_reel.py || exit 1
          if [ ! -f output/reel_*.mp4 ]; then
            echo "No reel was generated!"
            exit 1
          fi

      - name: Move reel to GitHub Pages folder
        run: |
          mkdir -p docs/output
          cp output/reel_*.mp4 docs/output/

      - name: Commit and push reel to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add message_tracker.json docs/output/reel_*.mp4
          git commit -m "Update message tracker and new reel" || exit 0
          git push

      - name: Upload to Instagram via Graph API
        run: |
          if [ -z "${{ secrets.IG_ACCESS_TOKEN }}" ] || [ -z "${{ secrets.IG_USER_ID }}" ]; then
            echo "Instagram credentials not set!"
            exit 1
          fi
          python upload_to_instagram.py || exit 1
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
