name: Daily Reel Generator

on:
  schedule:
    - cron: "30 11 * * *"  # 5:00 PM IST
    - cron: "30 14 * * *"  # 8:00 PM IST
    - cron: "30 16 * * *"  # 10:00 PM IST
    - cron: "30 17 * * *"  # 11:00 PM IST
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies (FFmpeg)
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Set up virtual environment & install requirements
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install --no-cache-dir -r requirements.txt

          mkdir -p output fonts

          if [ ! -f fonts/Montserrat-Bold.ttf ]; then
            wget -O fonts/Montserrat-Bold.ttf https://github.com/google/fonts/raw/main/ofl/montserrat/static/Montserrat-Bold.ttf
          fi

          if [ ! -f message_tracker.json ]; then
            echo '{"last_used_message": 0}' > message_tracker.json
          fi

      - name: Run script to generate reel (uses venv Python!)
        run: |
          ./venv/bin/python generate_reel.py

          if ! ls output/reel_*.mp4 1> /dev/null 2>&1; then
            echo "❌ No reel was generated!"
            exit 1
          fi

      - name: Move reel to GitHub Pages folder
        run: |
          mkdir -p docs/output
          cp output/reel_*.mp4 docs/output/

      - name: Commit and push reel to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add message_tracker.json docs/output/reel_*.mp4
          git commit -m "Update message tracker and new reel" || echo "Nothing to commit"
          git push

      - name: Upload to Instagram via Graph API
        run: |
          ./venv/bin/python upload_to_instagram.py
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
